apiVersion: apps/v1
kind: Deployment
metadata:
  name: churn-streamlit-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: churn-streamlit
  template:
    metadata:
      labels:
        app: churn-streamlit
    spec:
      containers:
      - name: churn-streamlit
        image: nitishrao/churn-streamlit-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: churn-streamlit-service
spec:
  type: NodePort
  selector:
    app: churn-streamlit
  ports:
  - protocol: TCP
    port: 8501
    targetPort: 8501
    nodePort: 30001
